# Lint, build, and test hippo on a push to main or a pull request

name: hippo-ci
permissions: read-all
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/hsaunders1904/hippo:latest

    steps:
    - uses: actions/checkout@v3
    - name: Quality Checks
      run: |
        # As we're running in our own container, we're not the same user as is
        # used by 'actions/checkout', so git operations fail.
        # https://github.com/actions/checkout/issues/766
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        pip install pre-commit
        pre-commit install
        pre-commit run --all
    - name: Build
      shell: bash
      run: |
        mkdir -p ~/.OpenFOAM
        cp ./scripts/openfoam-prefs.sh ~/.OpenFOAM/prefs.sh

        # This is just exiting with this message: 'Error: Process completed with exit code 1'
        . /opt/openfoam/OpenFOAM-10/etc/bashrc || true

        echo "FOAM_INST_DIR: ${FOAM_INST_DIR}"
        echo "WM_PROJECT_INST_DIR: ${WM_PROJECT_INST_DIR}"
        echo "WM_PROJECT_DIR: ${WM_PROJECT_DIR}"

        make
    - name: Test
      run: |
        # Fully expect this to fail as it requires 8 cores, but the GitHub
        # runners only have 2...
        ./run_tests
