# Lint, build, and test hippo on a push to main or a pull request

name: hippo-ci
permissions: read-all
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/hsaunders1904/hippo:latest

    steps:
    - uses: actions/checkout@v3
    - name: Quality Checks
      run: |
        # As we're running in our own container, we're not the same user as is
        # used by 'actions/checkout', so git operations fail.
        # https://github.com/actions/checkout/issues/766
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        pip install pre-commit
        pre-commit install
        pre-commit run --all
    - name: Build
      run: |
        ls
        echo "User: $(whoami)"
        echo "Home: ${HOME}"
        echo "~: $(cd ~ && pwd)"
        mkdir -p ~/.OpenFOAM
        cp ./scripts/openfoam-prefs.sh ~/.OpenFOAM/prefs.sh
        source /opt/openfoam/OpenFOAM-10/etc/bashrc
        make
    - name: Test
      run: |
        # Fully expect this to fail as it requires 8 cores, but the GitHub
        # runners only have 2...
        ./run_tests
