# Lint, build, and test hippo on a push to main or a pull request

name: hippo-ci
permissions: read-all
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          pip-install: pre-commit
          python-version: 3.14
      - name: Install apptainer
        run: |
          wget https://github.com/apptainer/apptainer/releases/download/v1.4.5/apptainer_1.4.5_amd64.deb
          sudo apt install -y ./apptainer_1.4.5_amd64.deb
          sudo sed -i 's/sessiondir max size = 64/sessiondir max size = 2000/' /etc/apptainer/apptainer.conf
      - name: Quality Checks
        run: |
          pip install pre-commit
          pre-commit install
          SKIP=no-commit-to-branch pre-commit run --all
      - name: Build apptainer production container
        run: sudo apptainer build hippo-release.sif apptainer/hippo-release.def
      - name: Test production container
        run: |
          apptainer exec --writable-tmpfs hippo-release.sif bash -c "cd /opt/hippo && ./run_tests"
      - name: Docs
        shell: bash
        run: |
          apptainer exec hippo-release.sif bash -c "cd /opt/hippo/doc && ./moosedocs.py build --destination=${{ github.workspace }}/doc/htmldoc"
          [ -f ${{ github.workspace }}/doc/htmldoc/index.html ]
      - name: Upload container artifact
        uses: actions/upload-artifact@v4
        with:
          name: apptainer-release-artefact
          path: hippo-release-${{ github.sha }}.sif
      - name: Artifact docs
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/doc/htmldoc

  deploy-docs:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build-test

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # Allow only one concurrent deployment, skipping runs queued between the
    # run in-progress and latest queued.
    # However, do NOT cancel in-progress runs as we want to allow these
    # production deployments to complete.
    concurrency:
      group: "pages"
      cancel-in-progress: false

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
