name: deploy-docker
on: workflow_dispatch
permissions: read-all

jobs:
  build-and-push:
    if: >
      github.actor == 'hsaunders1904' ||
      github.actor == 'dynamicist'
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_LOGIN_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./docker/Dockerfile
          tags: quay.io/hsaunders1904/hippo:latest
