# Build the hippo docker container and push it to Quay.io

name: deploy-docker
permissions: read-all
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "The tag for the image (e.g. latest, or 3.1.4)"
        required: true

jobs:
  build-and-push:
    if: >
      github.actor == 'hsaunders1904' ||
      github.actor == 'dynamicist'
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_LOGIN_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./docker/Dockerfile
          tags: quay.io/ukaea/hippo:${{ github.event.inputs.tag }}
